apiVersion: v1
kind: Pod
metadata:
  name: billingui
spec:
  hostNetwork: true
  containers:
    - name: billingui
      image: gcr.io/intrepid-kiln-174422/billing-ui
  nodeSelector:
    nodefor: uianddb